name: Code Check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  DashboardESLint:
    name: Dashboard ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dashboard/

    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: ESLint
      run: |
        npm install
        npm run lint

  FrontESlint:
    name: Front ESlint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front/

    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: ESLint
      run: |
        yarn
        yarn lint-strict

  FrontTSC:
    name: Front TSC
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front/

    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: yarn tsc --noEmit
      run: |
        yarn
        yarn tsc --noEmit
